# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # No mac os support rn.


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@v1

    - name: Install dependencies
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt install libc++-9-dev libc++abi-9-dev
        fi
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
            brew install coreutils

        fi
      shell: bash

    - name: Test
      run: ./test/main.sh
